/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Nodejs example
 * The nodejs API description
 * OpenAPI spec version: 1.0
 */
export type Authenticate401 = {
  error: string
  message: string
  statusCode: number
}

export type Authenticate200 = {
  token: string
}

export type ListPayables200Meta = {
  lastPage?: number
  page?: number
  total?: number
}

export type ListPayables200DataItemAssignor = {
  name?: string
}

export type ListPayables200DataItem = {
  assignor?: ListPayables200DataItemAssignor
  emissionDate?: string
  id?: string
  value?: number
}

export type ListPayables200 = {
  data?: ListPayables200DataItem[]
  meta?: ListPayables200Meta
}

export type AssignorControllerDelete200 = {
  document?: string
  email?: string
  id?: string
  name?: string
  phone?: string
}

export type AssignorControllerUpdate200 = {
  document?: string
  email?: string
  id?: string
  name?: string
  phone?: string
}

export type AssignorControllerGetById200 = {
  document?: string
  email?: string
  id?: string
  name?: string
  phone?: string
}

export type ListAssignors200Meta = {
  lastPage?: number
  page?: number
  total?: number
}

export type ListAssignors200DataItem = {
  document?: string
  email?: string
  id?: string
  name?: string
  phone?: string
}

export type ListAssignors200 = {
  data?: ListAssignors200DataItem[]
  meta?: ListAssignors200Meta
}

export type AssignorControllerCreate201 = {
  document?: string
  email?: string
  id?: string
  name?: string
  phone?: string
}

export interface AuthDto {
  [key: string]: unknown
}

export interface UpdatePayableDto {
  [key: string]: unknown
}

export interface CreatePayableDto {
  [key: string]: unknown
}

export interface CreatePayableAndAssignorDto {
  [key: string]: unknown
}

export interface UpdateAssignorDto {
  [key: string]: unknown
}

export interface CreateAssignorDto {
  [key: string]: unknown
}
