/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Nodejs example
 * The nodejs API description
 * OpenAPI spec version: 1.0
 */
export interface AuthDto {
  [key: string]: unknown
}

export interface UpdatePayableDto {
  [key: string]: unknown
}

export interface CreatePayableDto {
  [key: string]: unknown
}

export interface CreatePayableAndAssignorDto {
  [key: string]: unknown
}

export interface UpdateAssignorDto {
  [key: string]: unknown
}

export interface CreateAssignorDto {
  [key: string]: unknown
}
