/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Nodejs example
 * The nodejs API description
 * OpenAPI spec version: 1.0
 */
export type Authenticate200 = {
  token: string
}

export type AssignorControllerDelete200 = {
  document?: string
  email?: string
  id?: string
  name?: string
  phone?: string
}

export type AssignorControllerUpdate200 = {
  document?: string
  email?: string
  id?: string
  name?: string
  phone?: string
}

export type AssignorControllerGetById200 = {
  document?: string
  email?: string
  id?: string
  name?: string
  phone?: string
}

export type AssignorControllerListAll200Item = {
  document?: string
  email?: string
  id?: string
  name?: string
  phone?: string
}

export type AssignorControllerCreate201 = {
  document?: string
  email?: string
  id?: string
  name?: string
  phone?: string
}

export interface AuthDto {
  [key: string]: unknown
}

export interface UpdatePayableDto {
  [key: string]: unknown
}

export interface CreatePayableDto {
  [key: string]: unknown
}

export interface CreatePayableAndAssignorDto {
  [key: string]: unknown
}

export interface UpdateAssignorDto {
  [key: string]: unknown
}

export interface CreateAssignorDto {
  [key: string]: unknown
}
